version: '3.5'

services:
  node:
    image: gianiaz/node:latest
    depends_on:
      - db
    volumes:
      - .:/home/node/app

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestjs
    ports:
      - 3307:3306